### ISSUE TITLE
Request Schema - Allow PHP Array / JSON as input also

### ISSUE THREAD

**Issue by ssnukala** [userfrosting/fortress#1]
Currently the RequestSchema takes a file name as a param and loads the validation rules. 
Can we have it take an Array or JSON string directly and parse it ? 
This will help add validation rules dynamically.  Talking about Plugins adding validation rules dynamically in User Frosting.

**Comment by alexweissman** [comment]
Sure, we can do this.

**Comment by ssnukala** [comment]
Check this out
https://github.com/ssnukala/fortress/blob/master/fortress/RequestSchema.php#L28

**Comment by ssnukala** [comment]
I see the Request schema has been upgraded. 

any thoughts on opening up the schema to something other than the file ? would like the ability to pass JSON strong and dynamically append to the schema, before initiating the validation. 
Or will have to resort to writing to temp files and then passing that file to the RequestSchema.

**Comment by Silic0nS0ldier** [comment]
Would be nice to see this implemented at some point. Would really help with handling dynamic forms.

**Comment by alexweissman** [comment]
This will be possible in UF 4.1, because `RequestSchemaRepository` will extend a generic `Repository` class.  The `Repository` class has a `mergeItems` method that allows you to merge in additional values/subarrays at any key of your choosing.

Additionally, you will have access to the `set` and `unset` methods of `Repository` for more fine-grained manipulation of the schema.
