### ISSUE TITLE
Add validation support for uri slug

### ISSUE THREAD

**Issue by reblutus** [userfrosting/fortress#8]
In ServerSideValidator.php there is missing the uri that your WDVSS is supposed to support.

In generateSchemaRules you should add those lines:

```
                if ($validator_name == "uri"){
                    $this->ruleWithMessage("slug", $message_set, $field_name);
                }
```

Could also be a good idea to add this to ClientSideValidator class.

You also should support a sanitizer that swaps unwanted characters in '-' before validation.

**Comment by alexweissman** [comment]
Thanks!  Take a look at the 0.2.0 branch, we're deprecating the `ClientSideValidator` class in favor of separate classes for each compatible client-side library.  I think I've implemented `uri` for `JqueryValidationAdapter`, though not for `FormValidationAdapter`.

As for sanitization, I've realized since this project was started, that sanitizing data on input is rarely, if ever, a good idea.  The correct workflow is "validate on input, sanitize on output".  And, most modern templating languages (Twig, Blade, etc) handle sanitization automatically anyway!

**Comment by reblutus** [comment]
Hey! The thing that bothers me a lot in validate on input is, in many
times, the format required can be sanitize without annoying the user. For
example in this case for uri, lets say the user enters: "Chez André" I dont
want to give an error at this point saying "you can put accents", "your
can't put spaces" etc. I prefer the user is not bothered with those details
and sanitize the string in "chez-andre".

But maybe that's what you meant with sanitize on output...?

Oh and by the way I love your UserFrosting platform. Working on it for a
few weeks now and making many improvements.

Chears!

GB

**Comment by alexweissman** [comment]
Nice, glad you like UF!

So it sounds to me like you're trying to "slugify" the user's input (`Chez André => chez-andre`).  Are you storing both the original value and the slug in the DB?

**Comment by reblutus** [comment]
No just the slug.

GB

**Comment by alexweissman** [comment]
So maybe a better approach is to [not look at this as "sanitization" at all](http://security.stackexchange.com/questions/42498/which-is-the-best-way-to-sanitize-user-input-in-php/42521#42521).

You're transforming the user's input, sure, but that doesn't mean that their input is "wrong".  Instead, you're converting their input to a standard form.  That's fine, but depending on the situation, you might want to *show* your user how their input will be transformed.  Thanks to the magic of Javascript, you can do this in real time!

I'm not a huge fan of Wordpress, but I will use them as an example in this case because I think they got this right from a UX point of view.  Take a look at their "post editor":

![WP post editor showing slug](http://cdn.wpbeginner.com/wp-content/uploads/2013/04/post-slug.png)

It dynamically shows you what the resulting slug will be **as you type your input**.  You can accomplish this with some client-side slugifying code:

```
function slugify(text) {
    return text.toString().toLowerCase().trim()
        .replace(/&/g, '-and-')         // Replace & with 'and'
        .replace(/[\s\W-]+/g, '-')      // Replace spaces, non-word characters and dashes with a single dash (-)
}
```

You can tie this to your input field with a `.on('change', ...` event handler and show the target slug below the input field.

Then you can decide whether to have your page submit the generated slug (and validate that client-generated slug on the server!), or simply submit the original text and recreate the slug on the server side.

**Comment by reblutus** [comment]
Quick question, I get twig 1.24 but I can't use the dump function which is
in twig 1.5 Do you know why?

GB

**Comment by alexweissman** [comment]
This would probably be better discussed in our [chat](https://gitter.im/userfrosting/UserFrosting), or you can ask in Symfony (creator of Twig) freenode IRC chat: #symfony.

**Comment by alexweissman** [comment]
Uri validation is now supported in Fortress 2.
